name: conan-root-recipe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pre-commit>=2.8.2
  - isort>=5.5.3
  - mypy>=0.790
  - black>=19.10b0
  - flake8>=3.8.4
  - conan>=1.31.2
  